### ISSUE TITLE
Resolve issue where mute setting is not retained upon device reconnection to Home Assistant

### ISSUE THREAD

**Issue by MrWyss** [MrWyss/ha-assist-mic-satellite#24]
there is no check when device reconnects if it's in a mute state
```yaml
api:
  on_client_connected: 
    then:
      - delay: 10s
      - micro_wake_word.start
```
