### ISSUE TITLE
Remove repeat, screen is updated every 1s anyways

### ISSUE THREAD

**Issue by MrWyss** [MrWyss/ha-assist-mic-satellite#31]
just do

```yaml
          - script.execute: draw_display
          - wait_until:
              condition:
                binary_sensor.is_on: display_button
              timeout: 10s
```

https://github.com/MrWyss/ha-assist-mic-satellite/blob/e47599b0e289dc71b007a44b36c5954f0e09e729/code/esphome/va-mic-sat-atoms3.yaml#L200

https://github.com/MrWyss/ha-assist-mic-satellite/blob/e47599b0e289dc71b007a44b36c5954f0e09e729/code/esphome/va-mic-sat-atoms3.yaml#L220
